# CI de Nivel 04 - Disparo dos testes dentro do pipe de dev

name: 'Execução Integrada'

on:
  workflow_dispatch:

jobs:
  inspecao:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@V4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Checando padronizacao do código
        run: yarn lint

  unidade:
    runs-on: ubuntu-latest
    needs: [inspecao]

    steps:
      - uses: actions/checkout@V4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Executando testes de unidade
        run: yarn test

  # Versão corrigida do bloco e2e-tests:
  e2e-tests:
    runs-on: ubuntu-latest
    needs: [inspecao]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      # ❌ Removido: playwright
      # - name: Instalando Playwright
      #   run: yarn playwright install

      - name: Executando Testes E2E
        run: yarn run e2e

  deploy:
    runs-on: ubuntu-latest
    needs: [unidade, e2e-tests]

    steps:
      - name: Simulação do Deploy
        run: echo "simulando o deploy com sucesso"
